package:
  name: snakepipes
  version: 1.0.0_alpha5

source:
  path: ../

build:
  number: 0
  noarch: python
  skip: True  # [not py3k]

requirements:
  build:
    - python
  run:
    - python
    - snakemake 5.2.0
    - pandas
    - graphviz

test:
  commands:
    - DNA-mapping --help

about:
  home: 'https://snakepipes.readthedocs.org'
  license: GPLv3
  summary: NGS processing pipelines from the MPI-IE
